import java.io.*;
import java.lang.reflect.*;
import java.util.*;
import javax.microedition.lcdui.*;

/** Real dictionary construction, streams, precedence, text rendering and smile selection lifecycle. */
public class EmotionsProbe extends TextListProbe {
    static Class<?> emotions,smileIO;
    static Object emotionControl,previous;
    static TextBox draft;
    static Object value(String old,String name,Class<?> type)throws Exception{return f(emotions,old,name,type).get(null);}
    static Object smile(String name,Object...args)throws Exception{Class<?>[] types=name.equals("selectEmotion")?new Class<?>[]{TextBox.class,Object.class}:name.equals("commandAction")?new Class<?>[]{Command.class,Displayable.class}:name.equals("vlItemClicked")||name.equals("vlCursorMoved")?new Class<?>[]{vl}:name.equals("vlKeyPress")?new Class<?>[]{vl,int.class,int.class}:new Class<?>[0];String old=name.equals("vlItemClicked")?"b":name.equals("commandAction")?name:"a";try{return m(emotions,old,name,void.class,types).invoke(name.equals("selectEmotion")||name.equals("select")?null:emotionControl,args);}catch(InvocationTargetException e){if(e.getCause() instanceof Error)throw new AssertionError("Broken smile fixture: "+name,e.getCause());return "exception:"+e.getCause().getClass().getName();}}
    static void resetIO(boolean script)throws Exception{smileIO.getMethod("reset").invoke(null);smileIO.getField("scripted").setBoolean(null,script);}
    static void supply(String path,byte[] bytes)throws Exception{if(bytes!=null)((Hashtable)smileIO.getField("files").get(null)).put(path,bytes);}
    static String arrays()throws Exception{StringBuilder b=new StringBuilder();for(String[] names:new String[][]{{"a","selEmotionsIndexes"},{"b","textCorrIndexes"}})b.append(names[1]).append('=').append(Arrays.toString((int[])value(names[0],names[1],int[].class))).append(';');for(String[] names:new String[][]{{"a","selEmotionsWord"},{"b","selEmotionsSmileNames"},{"c","textCorrWords"}})b.append(names[1]).append('=').append(enc(Arrays.toString((String[])value(names[0],names[1],String[].class)))).append(';');return b.toString();}
    static void constructorState(String label)throws Exception{Object pictures=value("a","images",images);StringBuilder b=new StringBuilder(label+":used="+value("a","used",boolean.class)+":"+arrays()+":found="+Arrays.toString((boolean[])value("a","emoFinded",boolean[].class))+":images=");if(pictures==null)b.append("null");else{b.append(m(images,"a","size",int.class).invoke(pictures)).append(':').append(f(images,"a","width",int.class).getInt(pictures)).append(':').append(f(images,"b","height",int.class).getInt(pictures));for(int i=0;i<(Integer)m(images,"a","size",int.class).invoke(pictures);i++){Object iconValue=m(images,"a","elementAt",icon,int.class).invoke(pictures,i);b.append('[').append(m(icon,"a","getWidth",int.class).invoke(iconValue)).append(',').append(m(icon,"b","getHeight",int.class).invoke(iconValue)).append(']');}}b.append(":io=").append(smileIO.getField("log").get(null)).append(":closes=").append(smileIO.getField("closes").getInt(null)).append(":starts=").append(smileIO.getField("starts").getInt(null));row(b.toString());}
    static String definitions="16\n0,Smile,:-),:)\n1,Grin,:D,:DD\n2,Upper,AA,Aa\n3,Later,aa\n-1,Missing,:missing:\n99,Large,:large:\n4,Unicode,\u0423\u041b\u042b\u0411\u041a\u0410\n";
    static void load(String text,int image,int failure,boolean close,boolean stale,byte[] animation)throws Exception{
        resetIO(true);supply("/smiles.txt",text==null?null:text.getBytes("UTF-8"));supply("/smiles/animate.bin",animation);smileIO.getField("imageMode").setInt(null,image);smileIO.getField("failureAt").setInt(null,failure);smileIO.getField("failClose").setBoolean(null,close);
        if(!stale){for(String[] names:new String[][]{{"a","selEmotionsIndexes"},{"b","textCorrIndexes"}})f(emotions,names[0],names[1],int[].class).set(null,null);for(String[] names:new String[][]{{"a","selEmotionsWord"},{"b","selEmotionsSmileNames"},{"c","textCorrWords"}})f(emotions,names[0],names[1],String[].class).set(null,null);f(emotions,"a","emoFinded",boolean[].class).set(null,null);f(emotions,"a","images",images).set(null,null);}
        emotionControl=instance(emotions,new Class<?>[0]);
    }
    static void constructors()throws Exception{
        String[] texts={null,"","bad\n","16","16\n","16\nignored\n0,Name\n",definitions,"16\r\n0\tName\t:)\t :D \r\n","16\n0,Space,   , ,\n","16\n0,Empty,,alias\n","16\nnot-number,Name,:x:\n","16\n0,Name,:x:\nnot-number,Other,:y:\n","-1\n0,Name,:x:\n","100\n0,Name,:x:\n","16\n0,Name,:x:\n0,Again,:x:\n"};
        for(boolean stale:new boolean[]{false,true})for(int index=0;index<texts.length;index++)for(int image:new int[]{1,2,3}){if(stale){resetIO(false);emotionControl=instance(emotions,new Class<?>[0]);}load(texts[index],image,-1,false,stale,null);constructorState("constructor-"+stale+"-"+index+"-"+image);if(index==6&&image==1)validDictionary();}
        for(int failure:new int[]{0,1,2,3,6,16,40})for(boolean close:new boolean[]{false,true}){load(definitions,1,failure,close,false,null);constructorState("stream-failure-"+failure+"-"+close);}
        byte[][] data={{0},{1,4,2,0,1,1,2},{2,4,3,0,1,2,2,3,0,4,2,1,1,3,3},{2,4,3,0,1,2,2,3,0,4,0}};
        for(int i=0;i<data.length;i++){load(definitions,1,-1,false,false,data[i]);constructorState("animation-"+i);}
        Method insert=m(emotions,"a","insertTextCorr",void.class,Vector.class,String.class,Integer.class);Vector table=new Vector();for(String word:new String[]{"a","bbb","cc","BB","","cc","\u0423\u043b\u044b\u0431\u043a\u0430"}){insert.invoke(null,table,word,Integer.valueOf(table.size()));StringBuilder b=new StringBuilder("precedence-"+enc(word)+":");for(Object record:table)b.append(Arrays.toString((Object[])record));row(b.toString());}
    }
    static void readers()throws Exception{
        Method read=m(emotions,"a","readLineFromStream",String.class,DataInputStream.class);
        for(int value=0;value<256;value++){byte[] bytes={(byte)value,9,10,65,13,10};DataInputStream stream=new DataInputStream(new ByteArrayInputStream(bytes));for(int call=0;call<3;call++)row("byte-line-"+value+"-"+call+":"+enc(read.invoke(null,stream))+":left="+stream.available());}
        for(String value:new String[]{"","\n","one\r\nnext\n","\u0423\u043b\u044b\u0431\u043a\u0430\t\u010d\ud83d\ude00\n","\u0000\r\t\n","unfinished"})for(int at:new int[]{-1,0,1,2,4,10}){resetIO(true);supply("/smiles.txt",value.getBytes("UTF-8"));smileIO.getField("failureAt").setInt(null,at);InputStream bytes=(InputStream)smileIO.getMethod("open",Class.class,String.class).invoke(null,emotions,"/smiles.txt");DataInputStream stream=new DataInputStream(bytes);for(int call=0;call<4;call++)row("failure-line-"+enc(value)+"-"+at+"-"+call+":"+enc(read.invoke(null,stream)));}
    }
    static void validDictionary()throws Exception{if(!((Boolean)value("a","used",boolean.class))||((int[])value("a","selEmotionsIndexes",int[].class)).length!=7||((String[])value("c","textCorrWords",String[].class)).length!=10||(Integer)m(images,"a","size",int.class).invoke(value("a","images",images))!=8)throw new AssertionError("Valid scripted dictionary or image failed");}
    static void text()throws Exception{
        String[] messages={null,"","plain text","prefix :-):-) :D :DD :) :unknown:","AA aa Aa aA", "\u0443\u043b\u044b\u0431\u043a\u0430 \u0423\u041b\u042b\u0411\u041a\u0410",":missing: :large:","line\n:D\n:-)\r\nend", ":D"};
        for(int font:new int[]{0,8})for(int style:new int[]{0,1,2,3})for(int width:new int[]{60,176})for(boolean enabled:new boolean[]{false,true})for(int i=0;i<messages.length;i++){
            load(definitions,1,-1,false,false,null);validDictionary();fresh(font,style,width,130,3,1,true);bool(141,enabled);String label="text-"+font+"-"+style+"-"+width+"-"+enabled+"-"+i;Object result;try{m(emotions,"a","addTextWithEmotions",void.class,text,String.class,int.class,int.class,int.class).invoke(null,s,messages[i],style,0x123456,7);result=null;}catch(InvocationTargetException e){if(e.getCause() instanceof Error)throw new AssertionError(e.getCause());result="exception:"+e.getCause().getClass().getName();}row(label+":"+result+":flags="+Arrays.toString((boolean[])value("a","emoFinded",boolean[].class)));state(label);SelectorProbe.render(label,s);
        }
    }
    static Object grid()throws Exception{return value("a","selector",selector);}
    static void selectionState(String label,Object result)throws Exception{row(label+":"+result+":draft="+enc(draft.getString())+":caret="+value("b","caretPos",int.class)+":remembered="+value("a","lastSelectedEmotion",int.class)+":emotion="+enc(value("a","emotionText",String.class))+":grid="+(grid()!=null)+":returned="+(current()==previous||boundary.getField("screen").get(null)==previous)+":io="+smileIO.getField("log").get(null)+":collections="+smileIO.getField("collections").getInt(null));}
    static void selections()throws Exception{
        resetIO(false);emotionControl=instance(emotions,new Class<?>[0]);int last=((String[])value("a","selEmotionsWord",String[].class)).length-1;if(last<12)throw new AssertionError("Actual smile pack was not loaded");
        for(boolean remember:new boolean[]{false,true})for(boolean swap:new boolean[]{false,true})for(boolean nativePrevious:new boolean[]{false,true})for(int selected:new int[]{0,3,12,last})for(int caret:new int[]{-1,0,1,4,100})for(int mode=0;mode<5;mode++){
            resetIO(false);bool(163,remember);bool(143,swap);f(options,"g","fontStyle",int.class).setInt(null,2);m(vl,"d","assignSoftKeys",void.class).invoke(null);alpha(171,171,128);background(true);draft=new TextBox("Draft","ABCD",100,TextField.ANY);previous=nativePrevious?draft:make("Previous",176,220,3);f(emotions,"a","selector",selector).set(null,null);f(emotions,"a","lastSelectedEmotion",int.class).setInt(null,selected);smileIO.getField("caret").setInt(null,caret);boundary.getField("screen").set(null,null);Object opened=smile("selectEmotion",draft,previous);if(opened!=null)throw new AssertionError("Valid smile selector failed: "+opened);String label="select-"+remember+"-"+swap+"-"+nativePrevious+"-"+selected+"-"+caret+"-"+mode;selectionState(label+"-open",opened);Object active=grid();f(vl,"H","forcedWidth",int.class).setInt(active,176);f(vl,"I","forcedHeight",int.class).setInt(active,220);if(caret==1&&mode==0)SelectorProbe.render(label,active);
            Object result=mode==0?smile("commandAction",cmd("j","cmdSelect"),null):mode==1?smile("commandAction",cmd("c","cmdBack"),null):mode==2?smile("vlItemClicked",active):mode==3?smile("commandAction",new Command("Other",Command.SCREEN,5),null):invoke(m(vl,"c","keyReaction",void.class,int.class,int.class),active,-5,1);selectionState(label+"-finish",result);if(mode==3){smile("vlCursorMoved",active);smile("vlKeyPress",active,50,1);selectionState(label+"-noop",null);}
        }
        for(int capacity:new int[]{2,5,8})for(boolean remember:new boolean[]{false,true}){resetIO(false);bool(163,remember);draft=new TextBox("Draft","AB",capacity,TextField.ANY);previous=draft;f(emotions,"a","lastSelectedEmotion",int.class).setInt(null,3);smileIO.getField("caret").setInt(null,1);smile("selectEmotion",draft,previous);selectionState("capacity-"+capacity+"-"+remember,smile("commandAction",cmd("j","cmdSelect"),null));}
        // Caret is captured before a draft changes while its selector stays open.
        for(String changed:new String[]{"","x","a longer changed draft"}){resetIO(false);draft=new TextBox("Draft","ABCD",100,TextField.ANY);previous=draft;smileIO.getField("caret").setInt(null,3);smile("selectEmotion",draft,previous);draft.setString(changed);selectionState("changed-"+enc(changed),smile("commandAction",cmd("j","cmdSelect"),null));}
    }
    static void exerciseEmotions()throws Exception{setupFiles();emotions=load("bo","jimm.Emotions");smileIO=load("EmotionsIO","EmotionsIO");images=load("f","DrawControls.ImageList");icon=load("e","DrawControls.Icon");line=load("bm","DrawControls.TextLine");part=load("bc","DrawControls.TextItem");selector=load("af","jimm.util.Selector");boundary=load("MenuIO","MenuIO");shim=load("RecoveryList","RecoveryList");constructors();readers();text();selections();row("rasters:"+rasters);}
    public static void main(String[] args){try{run(args,new Exercise(){public void run()throws Exception{exerciseEmotions();}});System.exit(0);}catch(Throwable e){e.printStackTrace();System.exit(1);}}
}
