#!/usr/bin/env python3
"""Compare verified method signatures and normalized instructions with May bytecode.

This deliberately audits a named subset, not speculative whole-program symbol matches.
Different instruction sequences do not imply different behavior (see test_source.py).
"""
import hashlib
import json
import os
import re
import recover

ROOT = recover.ROOT
OUT = ROOT / 'build/source-audit'
CLASSES = {'co': 'jimm/comm/Util', 'cj': 'jimm/Options', 'z': 'jimm/ContactItem',
           'ci': 'DrawControls/VirtualAlert', 'cf': 'jimm/JimmUI',
           'ag': 'jimm/MainMenu', 'aq': 'jimm/Templates',
           'r': 'jimm/comm/Icq', 'n': 'jimm/comm/ConnectAction',
           'ap': 'jimm/comm/Icq$Connection', 'bv': 'jimm/JimmException',
           'cv': 'jimm/SplashCanvas', 'cd': 'DrawControls/VirtualList',
           'aa': 'jimm/comm/Action', 'at': 'jimm/TimerTasks', 'e': 'DrawControls/Icon',
           'ay': 'jimm/comm/Icq$HTTPConnection', 'cb': 'jimm/comm/Icq$SOCKSConnection',
           'an': 'jimm/comm/Packet', 'ct': 'jimm/comm/UpdateContactListAction',
           'bq': 'jimm/comm/OtherAction', 'ae': 'jimm/comm/ActionListener',
           'ac': 'jimm/comm/Message', 'ah': 'jimm/util/MagicEye', 'br': 'jimm/EditInfo', 'as': 'jimm/comm/SaveInfoAction',
           'ce': 'jimm/comm/RequestInfoAction', 'bi': 'DrawControls/TextList',
           'g': 'jimm/JimmUI$GetVersionInfoTimerTask', 'm': 'jimm/ContactList', 'cp': 'jimm/Search',
           'cr': 'jimm/Search$SearchForm', 'o': 'jimm/comm/SearchAction',
           'p': 'jimm/FileTransfer', 'u': 'jimm/FileBrowser', 'x': 'jimm/Traffic',
           'cc': 'jimm/FileTransfer$ViewFinder', 'd': 'DrawControls/VirtualForm',
           'j': 'DrawControls/FormChoiceGroup', 'k': 'jimm/FileBrowserListener',
           'aw': 'DrawControls/VirtualTree', 'ax': 'DrawControls/TreeNode', 'cn': 'DrawControls/ListItem',
           'ab': 'jimm/comm/FileTransferMessage', 'bw': 'jimm/comm/DirectConnectionAction',
           'ao': 'jimm/comm/Icq$PeerConnection', 'au': 'jimm/comm/DCPacket',
           'cl': 'jimm/comm/SendMessageAction', 'av': 'jimm/comm/PlainMessage',
           'a': 'jimm/Traffic$TrafficScreen', 'bl': 'jimm/XStatusForm', 'af': 'jimm/util/Selector', 'y': 'jimm/ChatTextList', 'bt': 'jimm/ChatHistory', 'ca': 'jimm/MessData', 'bo': 'jimm/Emotions'}
CLASSES.update({'q': 'jimm/HistoryStorage', 'bg': 'jimm/HistoryStorageList', 'bz': 'jimm/CachedRecord', 'w': 'jimm/FileSystem'})
SYMBOLS = {
    'q': 'jimm/HistoryStorage',
    'bg': 'jimm/HistoryStorageList',
    'bz': 'jimm/CachedRecord',
    'w': 'jimm/FileSystem',
    'q.<init>()V': 'jimm/HistoryStorage.<init>()V',
    'q.<clinit>()V': 'jimm/HistoryStorage.<clinit>()V',
    'q.a(Ljava/lang/String;Ljava/lang/String;BLjava/lang/String;J)V': 'jimm/HistoryStorage.addText(Ljava/lang/String;Ljava/lang/String;BLjava/lang/String;J)V',
    'q.a()Ljavax/microedition/rms/RecordStore;': 'jimm/HistoryStorage.getRS()Ljavax/microedition/rms/RecordStore;',
    'q.a(Ljava/lang/String;)Ljava/lang/String;': 'jimm/HistoryStorage.getRSName(Ljava/lang/String;)Ljava/lang/String;',
    'q.c(Ljava/lang/String;)V': 'jimm/HistoryStorage.openUINRecords(Ljava/lang/String;)V',
    'q.a(Ljava/lang/String;)I': 'jimm/HistoryStorage.getRecordCount(Ljava/lang/String;)I',
    'q.a(Ljava/lang/String;I)Lbz;': 'jimm/HistoryStorage.getRecord(Ljava/lang/String;I)Ljimm/CachedRecord;',
    'q.b(Ljava/lang/String;I)Lbz;': 'jimm/HistoryStorage.getCachedRecord(Ljava/lang/String;I)Ljimm/CachedRecord;',
    'q.a(Ljava/lang/String;Ljava/lang/String;)V': 'jimm/HistoryStorage.showHistoryList(Ljava/lang/String;Ljava/lang/String;)V',
    'q.a(Ljava/lang/String;)V': 'jimm/HistoryStorage.clearHistory(Ljava/lang/String;)V',
    'q.a()V': 'jimm/HistoryStorage.clearCache()V',
    'q.b()V': 'jimm/HistoryStorage.setColorScheme()V',
    'q.a(Ljava/lang/String;Ljava/lang/String;ZZ)Z': 'jimm/HistoryStorage.find_intern(Ljava/lang/String;Ljava/lang/String;ZZ)Z',
    'q.a(Ljava/lang/String;Ljava/lang/String;ZZ)V': 'jimm/HistoryStorage.find(Ljava/lang/String;Ljava/lang/String;ZZ)V',
    'q.b(Ljava/lang/String;)V': 'jimm/HistoryStorage.clear_all(Ljava/lang/String;)V',
    'bg.<init>()V': 'jimm/HistoryStorageList.<init>()V',
    'bg.<clinit>()V': 'jimm/HistoryStorageList.<clinit>()V',
    'bg.a(Lcd;)V': 'jimm/HistoryStorageList.vlCursorMoved(LDrawControls/VirtualList;)V',
    'bg.a(Lcd;II)V': 'jimm/HistoryStorageList.vlKeyPress(LDrawControls/VirtualList;II)V',
    'bg.d(Z)V': 'jimm/HistoryStorageList.copyText(Z)V',
    'bg.b(Lcd;)V': 'jimm/HistoryStorageList.vlItemClicked(LDrawControls/VirtualList;)V',
    'bg.a(I)V': 'jimm/HistoryStorageList.moveInList(I)V',
    'bg.a()Lz;': 'jimm/HistoryStorageList.getCItem()Ljimm/ContactItem;',
    'bg.d(Ljava/lang/String;)V': 'jimm/HistoryStorageList.export(Ljava/lang/String;)V',
    'bg.a(Ljava/lang/String;)V': 'jimm/HistoryStorageList.onFileSelect(Ljava/lang/String;)V',
    'bg.b(Ljava/lang/String;)V': 'jimm/HistoryStorageList.onDirectorySelect(Ljava/lang/String;)V',
    'bg.run()V': 'jimm/HistoryStorageList.run()V',
    'bg.a([Lz;)V': 'jimm/HistoryStorageList.startExport([Ljimm/ContactItem;)V',
    'bg.a(Ljava/lang/String;)Lw;': 'jimm/HistoryStorageList.openFile(Ljava/lang/String;)Ljimm/FileSystem;',
    'bg.commandAction(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V': 'jimm/HistoryStorageList.commandAction(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V',
    'bg.a()V': 'jimm/HistoryStorageList.showMessText()V',
    'bg.a()Ljava/lang/String;': 'jimm/HistoryStorageList.getCurrUin()Ljava/lang/String;',
    'bg.a$16da05f7(Ljava/lang/String;)V': 'jimm/HistoryStorageList.setCurrUin$16da05f7(Ljava/lang/String;)V',
    'bg.a()I': 'jimm/HistoryStorageList.getSize()I',
    'bg.a(ILcn;)V': 'jimm/HistoryStorageList.get(ILDrawControls/ListItem;)V',
    'q.a Ljavax/microedition/rms/RecordStore;': 'jimm/HistoryStorage.recordStore Ljavax/microedition/rms/RecordStore;',
    'q.a Lbg;': 'jimm/HistoryStorage.list Ljimm/HistoryStorageList;',
    'q.a Ljava/lang/String;': 'jimm/HistoryStorage.currCacheUin Ljava/lang/String;',
    'q.a Ljava/util/Hashtable;': 'jimm/HistoryStorage.cachedRecords Ljava/util/Hashtable;',
    'bg.c Ljavax/microedition/lcdui/Command;': 'jimm/HistoryStorageList.cmdMsgNext Ljavax/microedition/lcdui/Command;',
    'bg.d Ljavax/microedition/lcdui/Command;': 'jimm/HistoryStorageList.cmdMsgPrev Ljavax/microedition/lcdui/Command;',
    'bg.e Ljavax/microedition/lcdui/Command;': 'jimm/HistoryStorageList.cmdBack Ljavax/microedition/lcdui/Command;',
    'bg.f Ljavax/microedition/lcdui/Command;': 'jimm/HistoryStorageList.cmdClear Ljavax/microedition/lcdui/Command;',
    'bg.g Ljavax/microedition/lcdui/Command;': 'jimm/HistoryStorageList.cmdInfo Ljavax/microedition/lcdui/Command;',
    'bg.h Ljavax/microedition/lcdui/Command;': 'jimm/HistoryStorageList.cmdExport Ljavax/microedition/lcdui/Command;',
    'bg.i Ljavax/microedition/lcdui/Command;': 'jimm/HistoryStorageList.cmdExportAll Ljavax/microedition/lcdui/Command;',
    'bg.j Ljavax/microedition/lcdui/Command;': 'jimm/HistoryStorageList.cmdGotoURL Ljavax/microedition/lcdui/Command;',
    'bg.a Lbi;': 'jimm/HistoryStorageList.messText LDrawControls/TextList;',
    'bg.a Ljava/lang/String;': 'jimm/HistoryStorageList.currUin Ljava/lang/String;',
    'bg.a Ld;': 'jimm/HistoryStorageList.frmFind LDrawControls/VirtualForm;',
    'bg.a Ljavax/microedition/lcdui/TextField;': 'jimm/HistoryStorageList.tfldFind Ljavax/microedition/lcdui/TextField;',
    'bg.a Lj;': 'jimm/HistoryStorageList.chsFind LDrawControls/FormChoiceGroup;',
    'bg.b Z': 'jimm/HistoryStorageList.cp1251 Z',
    'bg.b Ljava/lang/String;': 'jimm/HistoryStorageList.exportUin Ljava/lang/String;',
    'bg.c Ljava/lang/String;': 'jimm/HistoryStorageList.directory Ljava/lang/String;',
    'bg.b Lbi;': 'jimm/HistoryStorageList.URLList LDrawControls/TextList;',
    'bz.a Ljava/lang/String;': 'jimm/CachedRecord.shortText Ljava/lang/String;',
    'bz.b Ljava/lang/String;': 'jimm/CachedRecord.text Ljava/lang/String;',
    'bz.c Ljava/lang/String;': 'jimm/CachedRecord.date Ljava/lang/String;',
    'bz.d Ljava/lang/String;': 'jimm/CachedRecord.from Ljava/lang/String;',
    'bz.a B': 'jimm/CachedRecord.type B',
    'bz.a Z': 'jimm/CachedRecord.contains_url Z',

    'y': 'jimm/ChatTextList',
    'bt': 'jimm/ChatHistory',
    'ca': 'jimm/MessData',
    'bo': 'jimm/Emotions',
    'y.a(Lz;)V': 'jimm/ChatTextList.buildMenu(Ljimm/ContactItem;)V',
    'y.a()Z': 'jimm/ChatTextList.isVisible()Z',
    'y.a()V': 'jimm/ChatTextList.removeAuthCommands()V',
    'y.a(Z)I': 'jimm/ChatTextList.getInOutColor(Z)I',
    'y.a(Lcd;)V': 'jimm/ChatTextList.vlCursorMoved(LDrawControls/VirtualList;)V',
    'y.b()V': 'jimm/ChatTextList.checkTextForURL()V',
    'y.c()V': 'jimm/ChatTextList.checkForAuthReply()V',
    'y.b(Lcd;)V': 'jimm/ChatTextList.vlItemClicked(LDrawControls/VirtualList;)V',
    'y.a(Lcd;II)V': 'jimm/ChatTextList.vlKeyPress(LDrawControls/VirtualList;II)V',
    'y.e()V': 'jimm/ChatTextList.activate()V',
    'y.<init>(Ljava/lang/String;Lz;)V': 'jimm/ChatTextList.<init>(Ljava/lang/String;Ljimm/ContactItem;)V',
    'y.commandAction(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V': 'jimm/ChatTextList.commandAction(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V',
    'y.<clinit>()V': 'jimm/ChatTextList.<clinit>()V',
    'bt.a(Lz;Lac;)V': 'jimm/ChatHistory.addMessage(Ljimm/ContactItem;Ljimm/comm/Message;)V',
    'bt.a(Ljava/lang/String;JZ)V': 'jimm/ChatHistory.AckMessage(Ljava/lang/String;JZ)V',
    'bt.a(Lz;Ljava/lang/String;JLjava/lang/String;J)V': 'jimm/ChatHistory.addMyMessage(Ljimm/ContactItem;Ljava/lang/String;JLjava/lang/String;J)V',
    'bt.a(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JZZLe;J)V': 'jimm/ChatHistory.addTextToForm(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JZZLDrawControls/Icon;J)V',
    'bt.a(Ljava/lang/String;Ljava/lang/String;)V': 'jimm/ChatHistory.copyText(Ljava/lang/String;Ljava/lang/String;)V',
    'bt.a(Ljava/lang/String;)Ly;': 'jimm/ChatHistory.getChatHistoryAt(Ljava/lang/String;)Ljimm/ChatTextList;',
    'bt.a(Ljava/lang/String;)V': 'jimm/ChatHistory.chatHistoryDelete(Ljava/lang/String;)V',
    'bt.a(Ljava/lang/String;I)V': 'jimm/ChatHistory.chatHistoryDelete(Ljava/lang/String;I)V',
    'bt.a(Ljava/lang/String;)Z': 'jimm/ChatHistory.chatHistoryShown(Ljava/lang/String;)Z',
    'bt.b(Ljava/lang/String;)Z': 'jimm/ChatHistory.chatHistoryExists(Ljava/lang/String;)Z',
    'bt.a(Lz;Ljava/lang/String;)V': 'jimm/ChatHistory.newChatForm(Ljimm/ContactItem;Ljava/lang/String;)V',
    'bt.a(Lz;)V': 'jimm/ChatHistory.fillFormHistory(Ljimm/ContactItem;)V',
    'bt.b(Ljava/lang/String;Ljava/lang/String;)V': 'jimm/ChatHistory.contactRenamed(Ljava/lang/String;Ljava/lang/String;)V',
    'bt.b(Ljava/lang/String;)V': 'jimm/ChatHistory.UpdateCaption(Ljava/lang/String;)V',
    'bt.a()V': 'jimm/ChatHistory.setColorScheme()V',
    'bt.c(Ljava/lang/String;)V': 'jimm/ChatHistory.calcCounter(Ljava/lang/String;)V',
    'bt.a(Lz;)Z': 'jimm/ChatHistory.activateIfExists(Ljimm/ContactItem;)Z',
    'bt.b(Lz;)V': 'jimm/ChatHistory.removeAuthCommands(Ljimm/ContactItem;)V',
    'bt.<init>()V': 'jimm/ChatHistory.<init>()V',
    'bt.<clinit>()V': 'jimm/ChatHistory.<clinit>()V',
    'ca.a()Z': 'jimm/MessData.getIncoming()Z',
    'ca.<init>(ZJIZ)V': 'jimm/MessData.<init>(ZJIZ)V',
    'bo.a(Ljava/util/Vector;Ljava/lang/String;Ljava/lang/Integer;)V': 'jimm/Emotions.insertTextCorr(Ljava/util/Vector;Ljava/lang/String;Ljava/lang/Integer;)V',
    'bo.a(Ljava/io/DataInputStream;)Ljava/lang/String;': 'jimm/Emotions.readLineFromStream(Ljava/io/DataInputStream;)Ljava/lang/String;',
    'bo.a(Lbi;Ljava/lang/String;III)V': 'jimm/Emotions.addTextWithEmotions(LDrawControls/TextList;Ljava/lang/String;III)V',
    'bo.a(Ljavax/microedition/lcdui/TextBox;Ljava/lang/Object;)V': 'jimm/Emotions.selectEmotion(Ljavax/microedition/lcdui/TextBox;Ljava/lang/Object;)V',
    'bo.a(Lcd;II)V': 'jimm/Emotions.vlKeyPress(LDrawControls/VirtualList;II)V',
    'bo.a(Lcd;)V': 'jimm/Emotions.vlCursorMoved(LDrawControls/VirtualList;)V',
    'bo.b(Lcd;)V': 'jimm/Emotions.vlItemClicked(LDrawControls/VirtualList;)V',
    'bo.a()V': 'jimm/Emotions.select()V',
    'bo.<init>()V': 'jimm/Emotions.<init>()V',
    'bo.commandAction(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V': 'jimm/Emotions.commandAction(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V',
    'bo.<clinit>()V': 'jimm/Emotions.<clinit>()V',
    'y.a Lbi;': 'jimm/ChatTextList.textList LDrawControls/TextList;',
    'y.a Ljava/lang/String;': 'jimm/ChatTextList.ChatName Ljava/lang/String;',
    'y.a Lz;': 'jimm/ChatTextList.contact Ljimm/ContactItem;',
    'y.a Ljava/util/Vector;': 'jimm/ChatTextList.messData Ljava/util/Vector;',
    'y.a I': 'jimm/ChatTextList.messTotalCounter I',
    'bt.a Ljava/util/Hashtable;': 'jimm/ChatHistory.historyTable Ljava/util/Hashtable;',
    'bt.a I': 'jimm/ChatHistory.counter I',
    'bt.a Le;': 'jimm/ChatHistory.image LDrawControls/Icon;',
    'ca.a J': 'jimm/MessData.time J',
    'ca.a I': 'jimm/MessData.rowData I',
    'bo.a [I': 'jimm/Emotions.selEmotionsIndexes [I',
    'bo.b [I': 'jimm/Emotions.textCorrIndexes [I',
    'bo.a [Ljava/lang/String;': 'jimm/Emotions.selEmotionsWord [Ljava/lang/String;',
    'bo.b [Ljava/lang/String;': 'jimm/Emotions.selEmotionsSmileNames [Ljava/lang/String;',
    'bo.c [Ljava/lang/String;': 'jimm/Emotions.textCorrWords [Ljava/lang/String;',
    'bo.a [Z': 'jimm/Emotions.emoFinded [Z',
    'bo.a I': 'jimm/Emotions.lastSelectedEmotion I',
    'bo.b I': 'jimm/Emotions.caretPos I',
    'bo.a Ljava/lang/String;': 'jimm/Emotions.emotionText Ljava/lang/String;',
    'bo.a Ljava/lang/Object;': 'jimm/Emotions.lastScreen Ljava/lang/Object;',
    'bo.a Ljavax/microedition/lcdui/TextBox;': 'jimm/Emotions.textBox Ljavax/microedition/lcdui/TextBox;',
    'bo.a Z': 'jimm/Emotions.used Z',
    'bo.a Ljava/util/Vector;': 'jimm/Emotions.findedEmotions Ljava/util/Vector;',
    'y.a Ljavax/microedition/lcdui/Command;': 'jimm/ChatTextList.cmdContactMenu Ljavax/microedition/lcdui/Command;',
    'y.b Ljavax/microedition/lcdui/Command;': 'jimm/ChatTextList.cmdMsgReply Ljavax/microedition/lcdui/Command;',
    'y.c Ljavax/microedition/lcdui/Command;': 'jimm/ChatTextList.cmdCloseChat Ljavax/microedition/lcdui/Command;',
    'y.d Ljavax/microedition/lcdui/Command;': 'jimm/ChatTextList.cmdDenyAuth Ljavax/microedition/lcdui/Command;',
    'y.e Ljavax/microedition/lcdui/Command;': 'jimm/ChatTextList.cmdReqAuth Ljavax/microedition/lcdui/Command;',
    'y.f Ljavax/microedition/lcdui/Command;': 'jimm/ChatTextList.cmdGrantAuth Ljavax/microedition/lcdui/Command;',
    'y.g Ljavax/microedition/lcdui/Command;': 'jimm/ChatTextList.cmdAddUrs Ljavax/microedition/lcdui/Command;',
    'y.h Ljavax/microedition/lcdui/Command;': 'jimm/ChatTextList.cmdAddToHistory Ljavax/microedition/lcdui/Command;',
    'y.i Ljavax/microedition/lcdui/Command;': 'jimm/ChatTextList.cmdDelChat Ljavax/microedition/lcdui/Command;',

    'bl': 'jimm/XStatusForm',
    'af': 'jimm/util/Selector',
    'bl.a Ld;': 'jimm/XStatusForm.form LDrawControls/VirtualForm;',
    'bl.a Ljavax/microedition/lcdui/TextField;': 'jimm/XStatusForm.titleTextField Ljavax/microedition/lcdui/TextField;',
    'bl.b Ljavax/microedition/lcdui/TextField;': 'jimm/XStatusForm.descTextField Ljavax/microedition/lcdui/TextField;',
    'bl.a Ljavax/microedition/lcdui/ChoiceGroup;': 'jimm/XStatusForm.choiceGroup Ljavax/microedition/lcdui/ChoiceGroup;',
    'bl.a Ljava/util/Vector;': 'jimm/XStatusForm.xstatusform Ljava/util/Vector;',
    'bl.a I': 'jimm/XStatusForm.xstIndex I',
    'bl.a Z': 'jimm/XStatusForm.happyFlag Z',
    'bl.<init>()V': 'jimm/XStatusForm.<init>()V',
    'bl.a(I)Ljava/lang/String;': 'jimm/XStatusForm.getRecordDesc(I)Ljava/lang/String;',
    'bl.a()Ljava/lang/String;': 'jimm/XStatusForm.saveInLine()Ljava/lang/String;',
    'bl.a([B)V': 'jimm/XStatusForm.LoadLineInTable([B)V',
    'ag.d()V': 'jimm/MainMenu.showXStatusSelector()V',
    'ag.a Laf;': 'jimm/MainMenu.selector Ljimm/util/Selector;',
    'ag.a Lag;': 'jimm/MainMenu._this Ljimm/MainMenu;',
    'af.<init>(II)V': 'jimm/util/Selector.<init>(II)V',
    'cv.f(Le;)V': 'jimm/SplashCanvas.setXStatusToDraw(LDrawControls/Icon;)V',
    'a': 'jimm/Traffic$TrafficScreen',
    'x.a La;': 'jimm/Traffic.trafficScreen Ljimm/Traffic$TrafficScreen;',
    'a.a Lbi;': 'jimm/Traffic$TrafficScreen.trafficTextList LDrawControls/TextList;',
    'a.a Ljavax/microedition/lcdui/Command;': 'jimm/Traffic$TrafficScreen.resetCommand Ljavax/microedition/lcdui/Command;',
    'a.b Ljavax/microedition/lcdui/Command;': 'jimm/Traffic$TrafficScreen.okCommand Ljavax/microedition/lcdui/Command;',
    'm.a(I)V': 'jimm/ContactList.updateTitle(I)V',
    'x.a I': 'jimm/Traffic.allInTraffic I',
    'x.b I': 'jimm/Traffic.allOutTraffic I',
    'x.c I': 'jimm/Traffic.savedCost I',
    'x.d I': 'jimm/Traffic.all_traffic I',
    'x.e I': 'jimm/Traffic.session_traffic I',
    'x.f I': 'jimm/Traffic.sessionInTraffic I',
    'x.g I': 'jimm/Traffic.sessionOutTraffic I',
    'x.h I': 'jimm/Traffic.costPerDaySum I',
    'x.a Ljava/util/Date;': 'jimm/Traffic.savedSince Ljava/util/Date;',
    'x.b Ljava/util/Date;': 'jimm/Traffic.lastTimeUsed Ljava/util/Date;',
    'x.<init>()V': 'jimm/Traffic.<init>()V',
    'x.a()V': 'jimm/Traffic.save()V',
    'x.a(I)Ljava/lang/String;': 'jimm/Traffic.getTrafficString(I)Ljava/lang/String;',
    'x.a()I': 'jimm/Traffic.getSessionTraffic()I',
    'x.a(I)V': 'jimm/Traffic.addInTraffic(I)V',
    'x.b(I)V': 'jimm/Traffic.addOutTraffic(I)V',
    'a.<init>()V': 'jimm/Traffic$TrafficScreen.<init>()V',
    'a.commandAction(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V': 'jimm/Traffic$TrafficScreen.commandAction(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V',

    'cl': 'jimm/comm/SendMessageAction',
    'av': 'jimm/comm/PlainMessage',
    'cl.a Lav;': 'jimm/comm/SendMessageAction.plainMsg Ljimm/comm/PlainMessage;',
    'cl.a Lab;': 'jimm/comm/SendMessageAction.fileTrans Ljimm/comm/FileTransferMessage;',
    'cl.a I': 'jimm/comm/SendMessageAction.SEQ1 I',
    'cl.b I': 'jimm/comm/SendMessageAction.msgId1 I',
    'cl.c I': 'jimm/comm/SendMessageAction.msgId2 I',
    'cl.d I': 'jimm/comm/SendMessageAction.msgCounter I',
    'cl.<init>(Lac;)V': 'jimm/comm/SendMessageAction.<init>(Ljimm/comm/Message;)V',
    'cl.a()J': 'jimm/comm/SendMessageAction.getMsgId()J',
    'cl.b()I': 'jimm/comm/SendMessageAction.getMsgCounter()I',
    'cl.a()V': 'jimm/comm/SendMessageAction.init()V',
    'cl.a(Lan;)Z': 'jimm/comm/SendMessageAction.forward(Ljimm/comm/Packet;)Z',
    'cl.a()Z': 'jimm/comm/SendMessageAction.isCompleted()Z',
    'cl.b()Z': 'jimm/comm/SendMessageAction.isError()Z',
    'cl.<clinit>()V': 'jimm/comm/SendMessageAction.<clinit>()V',

    'cc': 'jimm/FileTransfer$ViewFinder',
    'bw': 'jimm/comm/DirectConnectionAction',
    'ab': 'jimm/comm/FileTransferMessage',
    'ao': 'jimm/comm/Icq$PeerConnection',
    'au': 'jimm/comm/DCPacket',
    'cc.a Ljavax/microedition/media/Player;': 'jimm/FileTransfer$ViewFinder.p Ljavax/microedition/media/Player;',
    'cc.a Ljavax/microedition/media/control/VideoControl;': 'jimm/FileTransfer$ViewFinder.vc Ljavax/microedition/media/control/VideoControl;',
    'cc.a Z': 'jimm/FileTransfer$ViewFinder.active Z',
    'cc.b Z': 'jimm/FileTransfer$ViewFinder.viewfinder Z',
    'cc.a Ljavax/microedition/lcdui/Image;': 'jimm/FileTransfer$ViewFinder.img Ljavax/microedition/lcdui/Image;',
    'cc.a [B': 'jimm/FileTransfer$ViewFinder.data [B',
    'cc.a Lp;': 'jimm/FileTransfer$ViewFinder.this$0 Ljimm/FileTransfer;',
    'bw.a I': 'jimm/comm/DirectConnectionAction.state I',
    'bw.a Lab;': 'jimm/comm/DirectConnectionAction.ft Ljimm/comm/FileTransferMessage;',
    'bw.b I': 'jimm/comm/DirectConnectionAction.packets I',
    'bw.a J': 'jimm/comm/DirectConnectionAction.timestamp J',
    'bw.b Z': 'jimm/comm/DirectConnectionAction.cancel Z',
    'ab.a Ljava/lang/String;': 'jimm/comm/FileTransferMessage.filename Ljava/lang/String;',
    'ab.b Ljava/lang/String;': 'jimm/comm/FileTransferMessage.description Ljava/lang/String;',
    'ab.a Ljava/io/InputStream;': 'jimm/comm/FileTransferMessage.fis Ljava/io/InputStream;',
    'ab.a I': 'jimm/comm/FileTransferMessage.fsize I',
    'ao.a Ljavax/microedition/io/SocketConnection;': 'jimm/comm/Icq$PeerConnection.sc Ljavax/microedition/io/SocketConnection;',
    'ao.a Ljava/io/InputStream;': 'jimm/comm/Icq$PeerConnection.is Ljava/io/InputStream;',
    'ao.a Ljava/io/OutputStream;': 'jimm/comm/Icq$PeerConnection.os Ljava/io/OutputStream;',
    'ao.a Z': 'jimm/comm/Icq$PeerConnection.inputCloseFlag Z',
    'ao.a Ljava/lang/Thread;': 'jimm/comm/Icq$PeerConnection.rcvThread Ljava/lang/Thread;',
    'ao.a Ljava/util/Vector;': 'jimm/comm/Icq$PeerConnection.rcvdPackets Ljava/util/Vector;',
    'au.a [B': 'jimm/comm/DCPacket.data [B',
    'cc.<init>(Lp;)V': 'jimm/FileTransfer$ViewFinder.<init>(Ljimm/FileTransfer;)V',
    'cc.b()V': 'jimm/FileTransfer$ViewFinder.reset()V',
    'cc.paint(Ljavax/microedition/lcdui/Graphics;)V': 'jimm/FileTransfer$ViewFinder.paint(Ljavax/microedition/lcdui/Graphics;)V',
    'cc.a(Ljava/lang/String;)V': 'jimm/FileTransfer$ViewFinder.createPlayer(Ljava/lang/String;)V',
    'cc.a()V': 'jimm/FileTransfer$ViewFinder.start()V',
    'cc.a(Ljava/lang/String;)[B': 'jimm/FileTransfer$ViewFinder.getSnapshot(Ljava/lang/String;)[B',
    'cc.c()V': 'jimm/FileTransfer$ViewFinder.takeSnapshot()V',
    'cc.d()V': 'jimm/FileTransfer$ViewFinder.stop()V',
    'cc.commandAction(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V': 'jimm/FileTransfer$ViewFinder.commandAction(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V',
    'cc.e()V': 'jimm/FileTransfer$ViewFinder.openSendScreen()V',
    'cc.keyPressed(I)V': 'jimm/FileTransfer$ViewFinder.keyPressed(I)V',
    'bw.<init>(Lab;)V': 'jimm/comm/DirectConnectionAction.<init>(Ljimm/comm/FileTransferMessage;)V',
    'bw.a()V': 'jimm/comm/DirectConnectionAction.init()V',
    'bw.a(Lan;)Z': 'jimm/comm/DirectConnectionAction.forward(Ljimm/comm/Packet;)Z',
    'bw.a()I': 'jimm/comm/DirectConnectionAction.getProgress()I',
    'bw.a()Z': 'jimm/comm/DirectConnectionAction.isCompleted()Z',
    'bw.b()Z': 'jimm/comm/DirectConnectionAction.isError()Z',
    'bw.a(I)V': 'jimm/comm/DirectConnectionAction.onEvent(I)V',
    'ao.<init>()V': 'jimm/comm/Icq$PeerConnection.<init>()V',
    'ao.a(Ljava/lang/String;)V': 'jimm/comm/Icq$PeerConnection.connect(Ljava/lang/String;)V',
    'ao.a()V': 'jimm/comm/Icq$PeerConnection.close()V',
    'ao.a()I': 'jimm/comm/Icq$PeerConnection.available()I',
    'ao.a()Lan;': 'jimm/comm/Icq$PeerConnection.getPacket()Ljimm/comm/Packet;',
    'ao.a(Lan;)V': 'jimm/comm/Icq$PeerConnection.sendPacket(Ljimm/comm/Packet;)V',
    'ao.b()I': 'jimm/comm/Icq$PeerConnection.getLocalPort()I',
    'ao.a()[B': 'jimm/comm/Icq$PeerConnection.getLocalIP()[B',
    'ao.run()V': 'jimm/comm/Icq$PeerConnection.run()V',
    'au.<init>([B)V': 'jimm/comm/DCPacket.<init>([B)V',
    'au.a()[B': 'jimm/comm/DCPacket.toByteArray()[B',
    'ab.<init>(Ljava/lang/String;Lz;Ljava/lang/String;Ljava/lang/String;Ljava/io/InputStream;I)V': 'jimm/comm/FileTransferMessage.<init>(Ljava/lang/String;Ljimm/ContactItem;Ljava/lang/String;Ljava/lang/String;Ljava/io/InputStream;I)V',
    'ab.a(I)[B': 'jimm/comm/FileTransferMessage.getFileSegmentPacket(I)[B',
    'r.a Lao;': 'jimm/comm/Icq.peerC Ljimm/comm/Icq$PeerConnection;',

    'p.a I': 'jimm/FileTransfer.curMode I',
    'p.a Lcc;': 'jimm/FileTransfer.vf Ljimm/FileTransfer$ViewFinder;',
    'p.a Ld;': 'jimm/FileTransfer.name_Desc LDrawControls/VirtualForm;',
    'p.a Ljava/io/InputStream;': 'jimm/FileTransfer.fis Ljava/io/InputStream;',
    'p.b I': 'jimm/FileTransfer.fsize I',
    'p.a Ljava/lang/String;': 'jimm/FileTransfer.exceptionText Ljava/lang/String;',
    'p.a Ljavax/microedition/lcdui/TextField;': 'jimm/FileTransfer.fileNameField Ljavax/microedition/lcdui/TextField;',
    'p.b Ljavax/microedition/lcdui/TextField;': 'jimm/FileTransfer.descriptionField Ljavax/microedition/lcdui/TextField;',
    'p.a Lj;': 'jimm/FileTransfer.webTransfer LDrawControls/FormChoiceGroup;',
    'p.c I': 'jimm/FileTransfer.type I',
    'p.a Lz;': 'jimm/FileTransfer.cItem Ljimm/ContactItem;',
    'u.a Z': 'jimm/FileBrowser.needToSelectDirectory Z',
    'u.b Z': 'jimm/FileBrowser.returnToOptions Z',
    'u.a Lk;': 'jimm/FileBrowser.listener Ljimm/FileBrowserListener;',

    'o.a I': 'jimm/comm/SearchAction.state I',
    'o.a J': 'jimm/comm/SearchAction.lastActivity J',
    'o.a [Ljava/lang/String;': 'jimm/comm/SearchAction.search [Ljava/lang/String;',
    'o.a Lcp;': 'jimm/comm/SearchAction.cont Ljimm/Search;',
    'o.a [I': 'jimm/comm/SearchAction.ages [I',
    'cp.a Ljava/util/Vector;': 'jimm/Search.results Ljava/util/Vector;',
    'cp.a Z': 'jimm/Search.liteVersion Z',
    'cp.a Lcr;': 'jimm/Search.searchForm Ljimm/Search$SearchForm;',

    'as.a I': 'jimm/comm/SaveInfoAction.packetCounter I',
    'as.b I': 'jimm/comm/SaveInfoAction.errorCounter I',
    'as.a Ljava/util/Date;': 'jimm/comm/SaveInfoAction.init Ljava/util/Date;',

    'cf.c Ljava/lang/String;': 'jimm/JimmUI.clipBoardText Ljava/lang/String;',
    'cf.d Ljava/lang/String;': 'jimm/JimmUI.clipBoardHeader Ljava/lang/String;',
    'cf.e Ljava/lang/String;': 'jimm/JimmUI.clipBoardQuotedPrefix Ljava/lang/String;',
    'cf.f Ljava/lang/String;': 'jimm/JimmUI.clipBoardPlainText Ljava/lang/String;',
    'cf.a Z': 'jimm/JimmUI.clipBoardIncoming Z',
    'cf.a(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;': 'jimm/JimmUI.insertQuotingChars(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;',

    'co.a I': 'jimm/comm/Util.counter I',
    'ct.a I': 'jimm/comm/UpdateContactListAction.state I',
    'ct.c I': 'jimm/comm/UpdateContactListAction.errorCode I',
    'ct.a J': 'jimm/comm/UpdateContactListAction.lastActivity J',
    'co.a([BIIZ)Ljava/lang/String;': 'jimm/comm/Util.byteArrayToString([BIIZ)Ljava/lang/String;',
    'co.a(Ljava/lang/String;Z)[B': 'jimm/comm/Util.stringToByteArray(Ljava/lang/String;Z)[B',
    'co.a([B)[B': 'jimm/comm/Util.decipherPassword([B)[B',
    'cj.a(II)V': 'jimm/Options.setInt(II)V',
    'cj.a(IJ)V': 'jimm/Options.setLong(IJ)V',
    'cj.a(IZ)V': 'jimm/Options.setBoolean(IZ)V',
    'cj.a(ILjava/lang/String;)V': 'jimm/Options.setString(ILjava/lang/String;)V',
    'cj.a [Ljava/lang/Object;': 'jimm/Options.options [Ljava/lang/Object;',
    'z.a(I)Z': 'jimm/ContactItem.getBooleanValue(I)Z',
    'z.b(I)Z': 'jimm/ContactItem.hasCapability(I)Z',
    'z.b(I)I': 'jimm/ContactItem.getIntValue(I)I',
    'z.c(I)Z': 'jimm/ContactItem.isMessageAvailable(I)Z',
    'cf.a(Ljavax/microedition/lcdui/Command;I)I': 'jimm/JimmUI.getCommandType(Ljavax/microedition/lcdui/Command;I)I',
    'cf.b(Ljava/lang/Object;)V': 'jimm/JimmUI.selectScreen(Ljava/lang/Object;)V',
    'cf.c Ljavax/microedition/lcdui/Command;': 'jimm/JimmUI.cmdBack Ljavax/microedition/lcdui/Command;',
    'cf.a I': 'jimm/JimmUI.curScreenTag I',
    'ci.a Ljava/lang/Object;': 'DrawControls/VirtualAlert.previousScreen Ljava/lang/Object;',
    'ag.a(ZZ)V': 'jimm/MainMenu.doExit(ZZ)V',
    'aq.a()V': 'jimm/Templates.clearTemplates()V',
    'cf.e()V': 'jimm/JimmUI.menuRemoveContactSelected()V',
    'cf.f()V': 'jimm/JimmUI.menuRemoveMeSelected()V',
    'r.a I': 'jimm/comm/Icq.flapSEQ I',
    'r.a Lr;': 'jimm/comm/Icq._this Ljimm/comm/Icq;',
    'r.c Z': 'jimm/comm/Icq.disconnected Z',
    'n.b I': 'jimm/comm/ConnectAction.state I',
    'n.b Z': 'jimm/comm/ConnectAction.active Z',
    'n.c Z': 'jimm/comm/ConnectAction.cancel Z',
    'n.a J': 'jimm/comm/ConnectAction.lastActivity J',
    'n.a I': 'jimm/comm/ConnectAction.TIMEOUT I',
    'ap.a Ljava/lang/Object;': 'jimm/comm/Icq$Connection.closeLock Ljava/lang/Object;',
    'ap.a Z': 'jimm/comm/Icq$Connection.inputCloseFlag Z',
    'cv.a Lcv;': 'jimm/SplashCanvas._this Ljimm/SplashCanvas;',
    'cv.a Ljava/lang/String;': 'jimm/SplashCanvas.message Ljava/lang/String;',
    'cv.p I': 'jimm/SplashCanvas.progress I',
    'cv.r I': 'jimm/SplashCanvas.status_index I',
    'cv.c Z': 'jimm/SplashCanvas.isLocked Z',
    'cv.q I': 'jimm/SplashCanvas.availableMessages I',
    'cv.a Le;': 'jimm/SplashCanvas.xstatus_img LDrawControls/Icon;',
    'cv.a Lat;': 'jimm/SplashCanvas.actionTimer Ljimm/TimerTasks;',
    'cv.a Laa;': 'jimm/SplashCanvas.currentAction Ljimm/comm/Action;',
    'cv.c Ljavax/microedition/lcdui/Command;': 'jimm/SplashCanvas.cancelCommnad Ljavax/microedition/lcdui/Command;',
    'cv.r()V': 'jimm/SplashCanvas.cancelActionTimer()V',
    'aa.a(I)V': 'jimm/comm/Action.onEvent(I)V',
    'at.cancel()Z': 'jimm/TimerTasks.cancel()Z',
    'at.a Z': 'jimm/TimerTasks.wasError Z',
    'at.b Z': 'jimm/TimerTasks.canceled Z',
    'at.c I': 'jimm/TimerTasks.type I',
    'cd.e()V': 'DrawControls/VirtualList.repaint()V',
    'cd.a(Ljavax/microedition/lcdui/Command;I)V': 'DrawControls/VirtualList.addCommandEx(Ljavax/microedition/lcdui/Command;I)V',
    'cd.a(Ljavax/microedition/lcdui/Command;)V': 'DrawControls/VirtualList.removeCommandEx(Ljavax/microedition/lcdui/Command;)V',
    'cd.a(Ljavax/microedition/lcdui/CommandListener;)V': 'DrawControls/VirtualList.setCommandListener(Ljavax/microedition/lcdui/CommandListener;)V',
    'cd.l I': 'DrawControls/VirtualList.MENU_RIGHT_BAR I',
    'ap.a(Z)V': 'jimm/comm/Icq$Connection.setInputCloseFlag(Z)V',
    'ap.a()Z': 'jimm/comm/Icq$Connection.getInputCloseFlag()Z',
    'ay.a Ljavax/microedition/io/HttpConnection;': 'jimm/comm/Icq$HTTPConnection.hcm Ljavax/microedition/io/HttpConnection;',
    'ay.b Ljavax/microedition/io/HttpConnection;': 'jimm/comm/Icq$HTTPConnection.hcd Ljavax/microedition/io/HttpConnection;',
    'ay.a Ljava/io/InputStream;': 'jimm/comm/Icq$HTTPConnection.ism Ljava/io/InputStream;',
    'ay.a Ljava/io/OutputStream;': 'jimm/comm/Icq$HTTPConnection.osd Ljava/io/OutputStream;',
    'ay.a Ljava/lang/String;': 'jimm/comm/Icq$HTTPConnection.monitorURL Ljava/lang/String;',
    'ay.b Ljava/lang/String;': 'jimm/comm/Icq$HTTPConnection.sid Ljava/lang/String;',
    'ay.c Ljava/lang/String;': 'jimm/comm/Icq$HTTPConnection.proxy_host Ljava/lang/String;',
    'ay.a I': 'jimm/comm/Icq$HTTPConnection.seq I',
    'ay.b I': 'jimm/comm/Icq$HTTPConnection.proxy_port I',
    'ay.c I': 'jimm/comm/Icq$HTTPConnection.connSeq I',
    'ay.a(Lan;[BII)V': 'jimm/comm/Icq$HTTPConnection.sendPacket(Ljimm/comm/Packet;[BII)V',
    'ay.b()V': 'jimm/comm/Icq$HTTPConnection.stream_close()V',
    'cb.a Ljavax/microedition/io/SocketConnection;': 'jimm/comm/Icq$SOCKSConnection.sc Ljavax/microedition/io/SocketConnection;',
    'cb.a Ljava/io/InputStream;': 'jimm/comm/Icq$SOCKSConnection.is Ljava/io/InputStream;',
    'cb.a Ljava/io/OutputStream;': 'jimm/comm/Icq$SOCKSConnection.os Ljava/io/OutputStream;',
    'cb.a Z': 'jimm/comm/Icq$SOCKSConnection.is_connected Z',
    'cb.b()V': 'jimm/comm/Icq$SOCKSConnection.stream_close()V',
}
METHODS = [
    ('q', '<init>', '()V', '<init>'),
    ('q', '<clinit>', '()V', '<clinit>'),
    ('q', 'a', '(Ljava/lang/String;Ljava/lang/String;BLjava/lang/String;J)V', 'addText'),
    ('q', 'a', '()Ljavax/microedition/rms/RecordStore;', 'getRS'),
    ('q', 'a', '(Ljava/lang/String;)Ljava/lang/String;', 'getRSName'),
    ('q', 'c', '(Ljava/lang/String;)V', 'openUINRecords'),
    ('q', 'a', '(Ljava/lang/String;)I', 'getRecordCount'),
    ('q', 'a', '(Ljava/lang/String;I)Lbz;', 'getRecord'),
    ('q', 'b', '(Ljava/lang/String;I)Lbz;', 'getCachedRecord'),
    ('q', 'a', '(Ljava/lang/String;Ljava/lang/String;)V', 'showHistoryList'),
    ('q', 'a', '(Ljava/lang/String;)V', 'clearHistory'),
    ('q', 'a', '()V', 'clearCache'),
    ('q', 'b', '()V', 'setColorScheme'),
    ('q', 'a', '(Ljava/lang/String;Ljava/lang/String;ZZ)Z', 'find_intern'),
    ('q', 'a', '(Ljava/lang/String;Ljava/lang/String;ZZ)V', 'find'),
    ('q', 'b', '(Ljava/lang/String;)V', 'clear_all'),
    ('bg', '<init>', '()V', '<init>'),
    ('bg', '<clinit>', '()V', '<clinit>'),
    ('bg', 'a', '(Lcd;)V', 'vlCursorMoved'),
    ('bg', 'a', '(Lcd;II)V', 'vlKeyPress'),
    ('bg', 'd', '(Z)V', 'copyText'),
    ('bg', 'b', '(Lcd;)V', 'vlItemClicked'),
    ('bg', 'a', '(I)V', 'moveInList'),
    ('bg', 'a', '()Lz;', 'getCItem'),
    ('bg', 'd', '(Ljava/lang/String;)V', 'export'),
    ('bg', 'a', '(Ljava/lang/String;)V', 'onFileSelect'),
    ('bg', 'b', '(Ljava/lang/String;)V', 'onDirectorySelect'),
    ('bg', 'run', '()V', 'run'),
    ('bg', 'a', '([Lz;)V', 'startExport'),
    ('bg', 'a', '(Ljava/lang/String;)Lw;', 'openFile'),
    ('bg', 'commandAction', '(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V', 'commandAction'),
    ('bg', 'a', '()V', 'showMessText'),
    ('bg', 'a', '()Ljava/lang/String;', 'getCurrUin'),
    ('bg', 'a$16da05f7', '(Ljava/lang/String;)V', 'setCurrUin'),
    ('bg', 'a', '()I', 'getSize'),
    ('bg', 'a', '(ILcn;)V', 'get'),

    # ChatTextList appends/acks/accessors are inlined in the rebuilt JAR; ChatProbe exercises them.
    ('y', 'a', '(Lz;)V', 'buildMenu'),
    ('y', 'a', '()Z', 'isVisible'),
    ('y', 'a', '()V', 'removeAuthCommands'),
    ('y', 'a', '(Z)I', 'getInOutColor'),
    ('y', 'a', '(Lcd;)V', 'vlCursorMoved'),
    ('y', 'b', '()V', 'checkTextForURL'),
    ('y', 'c', '()V', 'checkForAuthReply'),
    ('y', 'b', '(Lcd;)V', 'vlItemClicked'),
    ('y', 'a', '(Lcd;II)V', 'vlKeyPress'),
    ('y', 'e', '()V', 'activate'),
    ('y', '<init>', '(Ljava/lang/String;Lz;)V', '<init>'),
    ('y', 'commandAction', '(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V', 'commandAction'),
    ('y', '<clinit>', '()V', '<clinit>'),
    ('bt', 'a', '(Lz;Lac;)V', 'addMessage'),
    ('bt', 'a', '(Ljava/lang/String;JZ)V', 'AckMessage'),
    ('bt', 'a', '(Lz;Ljava/lang/String;JLjava/lang/String;J)V', 'addMyMessage'),
    ('bt', 'a', '(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JZZLe;J)V', 'addTextToForm'),
    ('bt', 'a', '(Ljava/lang/String;Ljava/lang/String;)V', 'copyText'),
    ('bt', 'a', '(Ljava/lang/String;)Ly;', 'getChatHistoryAt'),
    ('bt', 'a', '(Ljava/lang/String;)V', 'chatHistoryDelete'),
    ('bt', 'a', '(Ljava/lang/String;I)V', 'chatHistoryDelete'),
    ('bt', 'a', '(Ljava/lang/String;)Z', 'chatHistoryShown'),
    ('bt', 'b', '(Ljava/lang/String;)Z', 'chatHistoryExists'),
    ('bt', 'a', '(Lz;Ljava/lang/String;)V', 'newChatForm'),
    ('bt', 'a', '(Lz;)V', 'fillFormHistory'),
    ('bt', 'b', '(Ljava/lang/String;Ljava/lang/String;)V', 'contactRenamed'),
    ('bt', 'b', '(Ljava/lang/String;)V', 'UpdateCaption'),
    ('bt', 'a', '()V', 'setColorScheme'),
    ('bt', 'c', '(Ljava/lang/String;)V', 'calcCounter'),
    ('bt', 'a', '(Lz;)Z', 'activateIfExists'),
    ('bt', 'b', '(Lz;)V', 'removeAuthCommands'),
    ('bt', '<init>', '()V', '<init>'),
    ('bt', '<clinit>', '()V', '<clinit>'),
    ('ca', 'a', '()Z', 'getIncoming'),
    ('ca', '<init>', '(ZJIZ)V', '<init>'),
    ('bo', 'a', '(Ljava/util/Vector;Ljava/lang/String;Ljava/lang/Integer;)V', 'insertTextCorr'),
    ('bo', 'a', '(Ljava/io/DataInputStream;)Ljava/lang/String;', 'readLineFromStream'),
    ('bo', 'a', '(Lbi;Ljava/lang/String;III)V', 'addTextWithEmotions'),
    ('bo', 'a', '(Ljavax/microedition/lcdui/TextBox;Ljava/lang/Object;)V', 'selectEmotion'),
    ('bo', 'a', '(Lcd;II)V', 'vlKeyPress'),
    ('bo', 'a', '(Lcd;)V', 'vlCursorMoved'),
    ('bo', 'b', '(Lcd;)V', 'vlItemClicked'),
    ('bo', 'a', '()V', 'select'),
    ('bo', '<init>', '()V', '<init>'),
    ('bo', 'commandAction', '(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V', 'commandAction'),
    ('bo', '<clinit>', '()V', '<clinit>'),

    ('bl', '<init>', '()V', '<init>'),
    ('bl', 'commandAction', '(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V', 'commandAction'),
    ('bl', 'a', '(I)Ljava/lang/String;', 'getRecordDesc'),
    ('bl', 'a', '()Ljava/lang/String;', 'saveInLine'),
    ('bl', 'a', '([B)V', 'LoadLineInTable'),
    ('ag', 'd', '()V', 'showXStatusSelector'),
    # TrafficScreen.update is specialized to ()V; TrafficProbe exercises the actual update(true) callers.
    ('x', '<init>', '()V', '<init>'),
    ('x', 'a', '()V', 'save'),
    ('x', 'a', '(I)Ljava/lang/String;', 'getTrafficString'),
    ('x', 'a', '()I', 'getSessionTraffic'),
    ('x', 'a', '(I)V', 'addInTraffic'),
    ('x', 'b', '(I)V', 'addOutTraffic'),
    ('a', '<init>', '()V', '<init>'),
    ('a', 'commandAction', '(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V', 'commandAction'),

    ('cl', '<init>', '(Lac;)V', '<init>'),
    # getMsgId is inlined in the rebuilt JAR; OutgoingProbe checks its ID arithmetic.
    ('cl', 'b', '()I', 'getMsgCounter'),
    ('cl', 'a', '()V', 'init'),
    ('cl', 'a', '(Lan;)Z', 'forward'),
    ('cl', 'a', '()Z', 'isCompleted'),
    ('cl', 'b', '()Z', 'isError'),
    ('cl', '<clinit>', '()V', '<clinit>'),

    ('cc', '<init>', '(Lp;)V', '<init>'),
    ('cc', 'b', '()V', 'reset'),
    ('cc', 'paint', '(Ljavax/microedition/lcdui/Graphics;)V', 'paint'),
    ('cc', 'a', '(Ljava/lang/String;)V', 'createPlayer'),
    ('cc', 'a', '()V', 'start'),
    ('cc', 'a', '(Ljava/lang/String;)[B', 'getSnapshot'),
    ('cc', 'c', '()V', 'takeSnapshot'),
    ('cc', 'd', '()V', 'stop'),
    ('cc', 'commandAction', '(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V', 'commandAction'),
    ('cc', 'e', '()V', 'openSendScreen'),
    ('cc', 'keyPressed', '(I)V', 'keyPressed'),
    ('bw', '<init>', '(Lab;)V', '<init>'),
    ('bw', 'a', '()V', 'init'),
    ('bw', 'a', '(Lan;)Z', 'forward'),
    ('bw', 'a', '()I', 'getProgress'),
    ('bw', 'a', '()Z', 'isCompleted'),
    ('bw', 'b', '()Z', 'isError'),
    ('bw', 'a', '(I)V', 'onEvent'),
    ('ao', '<init>', '()V', '<init>'),
    ('ao', 'a', '(Ljava/lang/String;)V', 'connect'),
    ('ao', 'a', '()V', 'close'),
    ('ao', 'a', '()I', 'available'),
    ('ao', 'a', '()Lan;', 'getPacket'),
    ('ao', 'a', '(Lan;)V', 'sendPacket'),
    ('ao', 'b', '()I', 'getLocalPort'),
    ('ao', 'a', '()[B', 'getLocalIP'),
    ('ao', 'run', '()V', 'run'),
    ('au', '<init>', '([B)V', '<init>'),
    ('au', 'a', '()[B', 'toByteArray'),
    ('ab', '<init>', '(Ljava/lang/String;Lz;Ljava/lang/String;Ljava/lang/String;Ljava/io/InputStream;I)V', '<init>'),
    ('ab', 'a', '(I)[B', 'getFileSegmentPacket'),

    ('p', '<init>', '(ILz;)V', '<init>'),
    ('p', 'a', '()Lz;', 'getCItem'),
    ('p', 'a', '(Ljava/io/InputStream;I)V', 'setData'),
    ('p', 'a', '()V', 'startFT'),
    ('p', 'run', '()V', 'run'),
    ('p', 'a', '(Ljava/lang/String;)V', 'onFileSelect'),
    ('p', 'b', '(Ljava/lang/String;)V', 'onDirectorySelect'),
    ('p', 'itemStateChanged', '(Ljavax/microedition/lcdui/Item;)V', 'itemStateChanged'),
    ('p', 'a', '(Ljava/lang/String;Ljava/lang/String;)V', 'askForNameDesc'),
    ('p', 'commandAction', '(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V', 'commandAction'),
    ('p', 'b', '()V', 'free'),
    ('u', '<init>', '()V', '<init>'),
    ('u', 'a', '(ZZ)V', 'setParameters'),
    ('u', 'a', '(Lk;)V', 'setListener'),
    ('u', 'a', '(Ljava/lang/String;)V', 'updateTreeCaptionAndCommands'),
    ('u', 'a', '(Lax;Lcn;)V', 'vtGetItemDrawData'),
    ('u', 'a', '()V', 'activate'),
    ('u', 'commandAction', '(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V', 'commandAction'),
    ('x', 'b', '(I)Ljava/lang/String;', 'getString'),
    ('x', 'a', '(Z)I', 'generateCostSum'),

    ('cp', '<init>', '(Z)V', '<init>'),
    ('cp', 'a', '(I)[Ljava/lang/String;', 'getResult'),
    ('cp', 'a', '()Lcr;', 'getSearchForm'),
    ('cr', '<init>', '(Lcp;)V', '<init>'),
    ('cr', 'a', '(I)V', 'activate'),
    ('cr', 'a', '(Z)V', 'nextOrPrev'),
    ('cr', 'a', '(Lcd;II)V', 'vlKeyPress'),
    ('cr', 'a', '(Lcd;)V', 'vlCursorMoved'),
    ('cr', 'b', '(Lcd;)V', 'vlItemClicked'),
    ('cr', 'commandAction', '(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V', 'commandAction'),
    ('o', '<init>', '(Lcp;[Ljava/lang/String;)V', '<init>'),
    ('o', 'a', '()V', 'init'),
    ('o', 'a', '(Lan;)Z', 'forward'),
    ('o', 'a', '(I)V', 'onEvent'),
    ('o', 'a', '()Z', 'isCompleted'),
    ('o', 'b', '()Z', 'isError'),

    ('cf', 'a', '(Lz;)V', 'showContactMenu'),
    ('cf', 'b', '(Lz;)V', 'addUser'),
    ('cf', 'c', '(Lz;)V', 'showClientInfo'),
    ('m', 'b', '(Z)V', 'afterConnect'),
    ('cf', 'b', '()V', 'about'),
    ('cf', 'a', '(Lbi;Ljava/lang/String;Le;IZ)V', 'addTextListItem'),
    ('cf', 'a', '(Lbi;Ljava/lang/String;Le;IZZ)V', 'addTextListItem'),
    ('g', 'run', '()V', 'run'),

    ('br', '<init>', '([Ljava/lang/String;Ljava/lang/Object;)V', '<init>'),
    ('br', 'run', '()V', 'run'),
    ('br', 'commandAction', '(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V', 'commandAction'),
    ('as', 'a', '()V', 'init'),
    ('as', 'a', '(Lan;)Z', 'forward'),
    ('as', 'a', '()Z', 'isCompleted'),
    ('as', 'b', '()Z', 'isError'),
    ('as', 'a', '()I', 'getProgress'),
    ('as', 'a', '(I)V', 'onEvent'),
    ('cf', 'a', '(Ljava/lang/String;Ljava/lang/String;)V', 'requiestUserInfo'),
    ('cf', 'a', '([Ljava/lang/String;Lbi;)V', 'fillUserInfo'),
    ('cf', 'a', '([Ljava/lang/String;)V', 'showUserInfo'),

    ('cf', 'a', '()Z', 'clipBoardIsEmpty'),
    ('cf', 'a', '(Z)Ljava/lang/String;', 'getClipBoardText'),
    ('cf', 'c', '()V', 'clearClipBoardText'),
    ('cf', 'a', '(ZLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V', 'setClipBoardText'),
    ('cf', 'a', '(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;', 'insertQuotingChars'),
    ('ah', 'a', '(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V', 'registerAction'),
    ('ah', 'a', '(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V', 'addAction'),
    ('ah', 'a', '(Ljava/lang/String;Ljava/lang/String;Z)V', 'addAction'),
    ('cd', 'a', '(I)Ljavax/microedition/lcdui/Command;', 'findMenuByType'),
    ('cd', 'a', '(Ljavax/microedition/lcdui/Command;I)V', 'addCommandEx'),
    ('cd', 'a', '(Ljavax/microedition/lcdui/Command;)V', 'removeCommandEx'),
    ('cd', 'm', '()V', 'removeAllCommands'),

    ('co', 'a', '(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)Ljava/lang/String;', 'replaceStr'),
    ('ae', 'a', '(Lan;)V', 'forward'),
    ('ae', 'a', '(Lz;)V', 'sendAutoMessage'),
    ('ae', 'a', '(Lac;)Z', 'isSpam'),
    ('co', 'b', '()I', 'createRandomId'),
    ('co', 'a', '()I', 'getCounter'),
    ('ct', 'a', '()V', 'init'),
    ('ct', 'a', '(Lan;)Z', 'forward'),
    ('ct', 'a', '()Z', 'isCompleted'),
    ('ct', 'b', '()Z', 'isError'),
    ('z', 'a', '(I[B)V', 'setIPValue'),
    ('z', 'a', '(I)[B', 'getIPValue'),
    ('ct', 'a', '(Lz;I)[B', 'packRosterItem'),
    ('n', 'a', '()V', 'init'),
    ('n', 'a', '(Lan;)Z', 'forward'),
    ('r', 'b', '(I)V', 'setXStatus'),
    ('bq', 'a', '(Z)V', 'setStandartUserInfo'),
    ('co', 'c', '([BII)Ljava/lang/String;', 'detectClientVersion'),
    ('co', 'a', '(I)I', 'translateStatusSend'),
    ('co', 'a', '(ILz;)I', 'translateStatusReceived'),
    ('cj', 'a', '(Ljava/io/DataInputStream;)V', 'readOptions'),
    ('cj', 'a', '(Ljava/io/DataOutputStream;)V', 'writeOptions'),
    ('z', 'a', '(I)I', 'getSortWeight'),
    ('ci', 'commandAction', '(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V', 'commandAction'),
    ('ag', 'a', '(ZZ)V', 'doExit'),
    ('aq', 'a', '()V', 'clearTemplates'),
    ('r', 'a', '()I', 'getFlapSequence'),
    ('r', 'b', '()I', 'getInitialFlapSequence'),
    ('r', 'a', '()Z', 'isDisconnected'),
    ('r', 'b', '(Z)V', 'setDisconnected'),
    ('r', 'a', '(I)Z', 'isNotCriticalConnectionError'),
    ('r', 'a', '(Z)V', 'disconnect'),
    ('r', 'e', '()V', 'resetServerCon'),
    ('n', 'a', '()Z', 'isCompleted'),
    ('n', 'b', '()Z', 'isError'),
    ('ap', 'a', '(Z)V', 'setInputCloseFlag'),
    ('ap', 'a', '()Z', 'getInputCloseFlag'),
    ('bv', 'a', '(Lbv;)V', 'handleException'),
    ('cv', 'a', '(Ljava/lang/String;)V', 'setMessage'),
    ('cv', 'a', '(I)V', 'setStatusToDraw'),
    ('cv', 'f', '(Le;)V', 'setXStatusToDraw'),
    ('cv', 'l', '(I)V', 'setProgress'),
    ('cv', 'b', '(Ljavax/microedition/lcdui/Command;)V', 'addCmd'),
    ('cv', 'c', '(Ljavax/microedition/lcdui/Command;)V', 'removeCmd'),
    ('cv', 'b', '(Ljavax/microedition/lcdui/CommandListener;)V', 'setCmdListener'),
    ('cv', 'd', '()Z', 'locked'),
    ('cv', 'o', '()V', 'messageAvailable'),
    ('cv', 'n', '()V', 'lockScreen'),
    ('cv', 'd', '(Z)V', 'unlock'),
    ('cv', 'a', '(Ljava/lang/String;Laa;Z)V', 'addTimerTask'),
    ('cv', 'r', '()V', 'cancelActionTimer'),
    ('cv', 'commandAction', '(Ljavax/microedition/lcdui/Command;Ljavax/microedition/lcdui/Displayable;)V', 'commandAction'),
    ('at', 'cancel', '()Z', 'cancel'),
    ('at', 'run', '()V', 'run'),
    ('ay', 'a', '(Ljava/lang/String;)V', 'connect'),
    ('ay', 'a', '(Lan;[BII)V', 'sendPacket'),
    ('ay', 'a', '(Lan;)V', 'sendPacket'),
    ('ay', 'run', '()V', 'run'),
    ('ay', 'b', '()V', 'stream_close'),
    ('ay', 'a', '()V', 'close'),
    ('cb', 'a', '(Ljava/lang/String;)V', 'connect'),
    ('cb', 'a', '(BLjava/lang/String;Ljava/lang/String;)V', 'connect_socks'),
    ('cb', 'b', '()V', 'stream_close'),
    ('cb', 'a', '()V', 'close'),
]


def normalized(code):
    result = []
    for instruction in code:
        # A short obfuscated owner (e.g. o) must not match the suffix of co.
        opcode, separator, operand = instruction.partition(' ')
        if operand in SYMBOLS:
            instruction = opcode + separator + SYMBOLS[operand]
        for before, after in CLASSES.items():
            instruction = instruction.replace('L' + before + ';', 'L' + after + ';')
        result.append(instruction)
    return result


def digest(code):
    return hashlib.sha256('\n'.join(code).encode()).hexdigest()


def normalized_handlers(handlers):
    result = []
    for entry in handlers:
        region, _, exception = entry.rpartition(' ')
        result.append(region + ' ' + CLASSES.get(exception, exception))
    return result


def main():
    recover.bootstrap()
    OUT.mkdir(parents=True, exist_ok=True)
    cp = recover.cp([recover.CACHE / n for n in recover.ASM])
    recover.run([os.environ.get('JAVAC', 'javac'), '-cp', cp, '-d', OUT,
                 ROOT / 'tools/recovery/BytecodeDump.java'])
    def dump(path):
        data = json.loads(recover.run([recover.java(), '-cp', recover.cp([OUT, cp]),
                                      'BytecodeDump', path], capture=True))
        return {c['name']: c for c in data}
    reference = ROOT / 'preservation/wayback-originals/Jimm_MIDP2_RU/Jimm.jar'
    rebuilt = ROOT / 'build/source/MIDP2-RU/preverified.jar'
    old, new = dump(reference), dump(rebuilt)
    methods = []
    for owner, name, desc, source_name in METHODS:
        before = next(m for m in old[owner]['methods'] if (m['name'], m['desc']) == (name, desc))
        source_desc = desc
        for short, long in CLASSES.items():
            source_desc = source_desc.replace('L' + short + ';', 'L' + long + ';')
        after = next(m for m in new[CLASSES[owner]]['methods']
                     if m['name'].split('$')[0] == source_name and m['desc'] == source_desc)
        left, right = normalized(before['code']), after['code']
        same_static = bool(before['access'] & 8) == bool(after['access'] & 8)
        if not same_static:
            raise AssertionError('Static/instance mismatch: ' + owner + '.' + name + desc)
        same_synchronized = bool(before['access'] & 32) == bool(after['access'] & 32)
        if not same_synchronized:
            raise AssertionError('Synchronization mismatch: ' + owner + '.' + name + desc)
        same_handlers = normalized_handlers(before['handlers']) == after['handlers']
        methods.append({'reference': owner + '.' + name + desc,
                        'source': CLASSES[owner] + '.' + after['name'] + source_desc,
                        'signature_verified': True, 'static_modifier_verified': same_static,
                        'synchronized_modifier_verified': same_synchronized,
                        'reference_instructions': len(left),
                        'source_instructions': len(right), 'same_normalized_instructions': left == right,
                        'same_normalized_handlers': same_handlers,
                        'same_normalized_bytecode': left == right and same_handlers,
                        'reference_normalized_sha256': digest(left), 'source_normalized_sha256': digest(right)})
    report = {'reference_sha256': recover.sha(reference), 'rebuilt_sha256': recover.sha(rebuilt),
              'reference_classes': len(old), 'rebuilt_classes': len(new), 'methods': methods,
              'scope': 'Verified subset only. Instruction equality includes local slots and branch layout; '
                       'compiler and optimizer differences remain. Functional checks are recorded separately.'}
    path = ROOT / 'preservation/reports/source-bytecode-comparison.json'
    path.write_text(json.dumps(report, indent=2) + '\n', encoding='utf-8')
    print('Audited', len(methods), 'method signatures;', sum(m['same_normalized_instructions'] for m in methods),
          'identical normalized instruction sequences;', sum(m['same_normalized_bytecode'] for m in methods),
          'also match exception tables')


if __name__ == '__main__':
    main()
